/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as TournamentsTournamentIdImport } from './routes/tournaments/$tournamentId'
import { Route as TournamentsTournamentIdIndexImport } from './routes/tournaments/$tournamentId/index'
import { Route as TournamentsTournamentIdPointsImport } from './routes/tournaments/$tournamentId/points'
import { Route as TournamentsTournamentIdAwardsImport } from './routes/tournaments/$tournamentId/awards'
import { Route as TournamentsTournamentIdUserIdImport } from './routes/tournaments/$tournamentId/$userId'
import { Route as TournamentsTournamentIdMatchesMatchIdImport } from './routes/tournaments/$tournamentId/matches/$matchId'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TournamentsTournamentIdRoute = TournamentsTournamentIdImport.update({
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRoute,
} as any)

const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexImport.update({
    path: '/',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)

const TournamentsTournamentIdPointsRoute =
  TournamentsTournamentIdPointsImport.update({
    path: '/points',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)

const TournamentsTournamentIdAwardsRoute =
  TournamentsTournamentIdAwardsImport.update({
    path: '/awards',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)

const TournamentsTournamentIdUserIdRoute =
  TournamentsTournamentIdUserIdImport.update({
    path: '/$userId',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)

const TournamentsTournamentIdMatchesMatchIdRoute =
  TournamentsTournamentIdMatchesMatchIdImport.update({
    path: '/matches/$matchId',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdImport
      parentRoute: typeof rootRoute
    }
    '/tournaments/$tournamentId/$userId': {
      id: '/tournaments/$tournamentId/$userId'
      path: '/$userId'
      fullPath: '/tournaments/$tournamentId/$userId'
      preLoaderRoute: typeof TournamentsTournamentIdUserIdImport
      parentRoute: typeof TournamentsTournamentIdImport
    }
    '/tournaments/$tournamentId/awards': {
      id: '/tournaments/$tournamentId/awards'
      path: '/awards'
      fullPath: '/tournaments/$tournamentId/awards'
      preLoaderRoute: typeof TournamentsTournamentIdAwardsImport
      parentRoute: typeof TournamentsTournamentIdImport
    }
    '/tournaments/$tournamentId/points': {
      id: '/tournaments/$tournamentId/points'
      path: '/points'
      fullPath: '/tournaments/$tournamentId/points'
      preLoaderRoute: typeof TournamentsTournamentIdPointsImport
      parentRoute: typeof TournamentsTournamentIdImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/'
      fullPath: '/tournaments/$tournamentId/'
      preLoaderRoute: typeof TournamentsTournamentIdIndexImport
      parentRoute: typeof TournamentsTournamentIdImport
    }
    '/tournaments/$tournamentId/matches/$matchId': {
      id: '/tournaments/$tournamentId/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/tournaments/$tournamentId/matches/$matchId'
      preLoaderRoute: typeof TournamentsTournamentIdMatchesMatchIdImport
      parentRoute: typeof TournamentsTournamentIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AdminRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute.addChildren({
    TournamentsTournamentIdUserIdRoute,
    TournamentsTournamentIdAwardsRoute,
    TournamentsTournamentIdPointsRoute,
    TournamentsTournamentIdIndexRoute,
    TournamentsTournamentIdMatchesMatchIdRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/tournaments/$tournamentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/tournaments/$tournamentId": {
      "filePath": "tournaments/$tournamentId.tsx",
      "children": [
        "/tournaments/$tournamentId/$userId",
        "/tournaments/$tournamentId/awards",
        "/tournaments/$tournamentId/points",
        "/tournaments/$tournamentId/",
        "/tournaments/$tournamentId/matches/$matchId"
      ]
    },
    "/tournaments/$tournamentId/$userId": {
      "filePath": "tournaments/$tournamentId/$userId.tsx",
      "parent": "/tournaments/$tournamentId"
    },
    "/tournaments/$tournamentId/awards": {
      "filePath": "tournaments/$tournamentId/awards.tsx",
      "parent": "/tournaments/$tournamentId"
    },
    "/tournaments/$tournamentId/points": {
      "filePath": "tournaments/$tournamentId/points.tsx",
      "parent": "/tournaments/$tournamentId"
    },
    "/tournaments/$tournamentId/": {
      "filePath": "tournaments/$tournamentId/index.tsx",
      "parent": "/tournaments/$tournamentId"
    },
    "/tournaments/$tournamentId/matches/$matchId": {
      "filePath": "tournaments/$tournamentId/matches/$matchId.tsx",
      "parent": "/tournaments/$tournamentId"
    }
  }
}
ROUTE_MANIFEST_END */
